name: Run e2e tests

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          
      - name: Build
        run: |
         npm install -g @angular/cli
         npm install
         node ./.github/workflows/replace-env.js
         mkdir -p assets
         echo "${{ secrets.API_KEY }}" > assets/API_KEY
         ng build
        env:
          API_KEY: ${{ secrets.API_KEY }}
          
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start
