name: Run e2e tests

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Setup
        run: |
          npm install -g @angular/cli
          npm install
          node ./.github/workflows/replace-env.js
          ng build
          mkdir -p assets
          echo "$API_KEY" > assets/API_KEY
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
